<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Silk.NET.Input" />
      <PackageReference Include="Silk.NET.Maths" />
      <PackageReference Include="Silk.NET.OpenGL" />
      <PackageReference Include="Silk.NET.Windowing" />
      <PackageReference Include="StbTrueTypeSharp" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Engine\Engine.csproj" />
      <ProjectReference Include="..\Database\Database.csproj" />
      <ProjectReference Include="..\OpenGL\OpenGL.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update=".\Assets/JetBrainsMono-Bold.ttf">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>
</Project>
