<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Engine\Engine.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update=".\Assets/JetBrainsMono-Bold.ttf">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>
</Project>
