<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Silk.NET.Input" />
      <PackageReference Include="Silk.NET.Input.Glfw" />
      <PackageReference Include="Silk.NET.Maths" />
      <PackageReference Include="Silk.NET.Windowing" />
      <PackageReference Include="Silk.NET.Windowing.Glfw" />
      <PackageReference Include="Silk.NET.OpenGL" />
      <PackageReference Include="StbTrueTypeSharp" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="ECS\" />
      <Folder Include="Enums\" />
      <Folder Include="Input\" />
      <Folder Include="Render\" />
      <Folder Include="Terrain\" />
      <Folder Include="Utilities\" />
    </ItemGroup>
</Project>
